@echo off
echo Starting SecureVault...

echo Starting Frontend...
start cmd /k "cd /d C:\Users\darth\OneDrive\Desktop\securevault\frontend && npm run dev"

echo Starting Backend...
start cmd /k "cd /d C:\Users\darth\OneDrive\Desktop\securevault\backend && set SECURITY_SERVICE_URL=http://localhost:8001 && npm run dev"

echo Starting Security Service...
start cmd /k "cd /d C:\Users\darth\OneDrive\Desktop\securevault\security-service && start.bat"

echo All services started!